import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.*;

@SpringBootApplication
@RestController
public class TestAgentApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestAgentApplication.class, args);
    }

    // This handles the button click from your index.html
    @PostMapping("/generate-test")
    public String generateTest(@RequestBody java.util.Map<String, String> payload) {
        String code = payload.get("code");

        // This is a placeholder. Soon we will connect the real AI Agent here!
        return "/* GENERATED BY AI AGENT */\n\n" +
                "@Test\n" +
                "void autoGeneratedTest() {\n" +
                "    // Analyzing code: " + (code != null ? code.substring(0, Math.min(10, code.length())) : "") + "...\n" +
                "    assertTrue(true);\n" +
                "}";
    }
}